### ISSUE TITLE
v0.0.6 manifest.json had unexpected number of entries: 2

### ISSUE THREAD

**Issue by floragj** [paketo-buildpacks/nodejs#233] opened 2020-08-28 18:59 UTC
Attempted to build this [Paketo sample rack app](https://github.com/kvedurmu/paketo-samples/tree/master/ruby/rack/hello_rails) with the command:

```
pack build rails-rack-app --buildpack gcr.io/paketo-buildpacks/nodejs --buildpack gcr.io/paketo-community/ruby
```

And got the output:
```
ERROR: failed to build: opening buildpack blob: extracting buildpack paketo-buildpacks/nodejs@0.0.6 layer (diffID sha256:0c670b1d33c9f41a33ce38fabc8cd69def4379a04c64a09b12b31b0736f263c4): manifest.json had unexpected number of entries: 2
```

This seems related to [this Ruby issue](https://github.com/paketo-community/ruby/issues/79).

**Comment by arjun024** [comment] 2020-08-28 20:23
I'm unable to reproduce the issue. Used nodejs `0.0.6` and ruby `0.0.16` (latest).

`pack build rackapp --buildpack gcr.io/paketo-buildpacks/nodejs:0.0.6 --buildpack gcr.io/paketo-community/ruby:0.0.16`

The app built successfully and ran fine.
What versions did you use?

**Comment by floragj** [comment] 2020-08-28 21:53
As far as `pack` can tell, it's using the `latest` tag of the buildpack:

```
pack build rails-rack-app --buildpack gcr.io/paketo-buildpacks/nodejs --buildpack gcr.io/paketo-community/ruby
base: Pulling from paketobuildpacks/builder
Digest: sha256:83c60fcd6def0a3b6f9a1cbf049345a54dd43b6603041d19d61c08c46edd7185
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:30cd86c9a265a39629421fea0172be15cd4aefb9f7f432e98a330583196f172e
Status: Image is up to date for paketobuildpacks/run:base-cnb
latest: Pulling from paketo-buildpacks/nodejs
Digest: sha256:314cd0a2ddd6e87d3c1a064627a64e0b63299761595efee06d707c98dab07101
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:latest
latest: Pulling from paketo-community/ruby
Digest: sha256:8442aecf21e6f19fe35efd603a66ded6561bf96cb80a8add2007082915d79665
Status: Image is up to date for gcr.io/paketo-community/ruby:latest
```

However, when I `pack build` with the version tags specified, I get the following output:
```
pack build rails-rack-app --buildpack gcr.io/paketo-buildpacks/nodejs:0.0.6 --buildpack gcr.io/paketo-community/ruby:0.0.16
base: Pulling from paketobuildpacks/builder
Digest: sha256:83c60fcd6def0a3b6f9a1cbf049345a54dd43b6603041d19d61c08c46edd7185
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:30cd86c9a265a39629421fea0172be15cd4aefb9f7f432e98a330583196f172e
Status: Image is up to date for paketobuildpacks/run:base-cnb
0.0.6: Pulling from paketo-buildpacks/nodejs
Digest: sha256:314cd0a2ddd6e87d3c1a064627a64e0b63299761595efee06d707c98dab07101
Status: Downloaded newer image for gcr.io/paketo-buildpacks/nodejs:0.0.6
0.0.16: Pulling from paketo-community/ruby
Digest: sha256:8442aecf21e6f19fe35efd603a66ded6561bf96cb80a8add2007082915d79665
Status: Downloaded newer image for gcr.io/paketo-community/ruby:0.0.16
0.9.1: Pulling from buildpacksio/lifecycle
Digest: sha256:53bf0e18a734e0c4071aa39b950ed8841f82936e53fb2a0df56c6aa07f9c5023
Status: Image is up to date for buildpacksio/lifecycle:0.9.1
```

It seems that the `latest` tag for the nodejs buildpack isn't pointing at the same image as the `0.0.6` tag.

**Comment by arjun024** [comment] 2020-08-31 14:10
As of date, the `latest` tags are same as nodejs `0.0.6` and ruby `0.0.16`. What version of pack are you using?
If you're using 0.13, can you try with 0.11 or 0.12?

**Comment by kvedurmu** [comment] 2020-09-01 20:52
I run into this occasionally with all Paketo Buildpacks (you can find several threads in slack around this). As the prior message suggests, I always reference buildpackages explicitly with their tag to avoid this issue. This might be something worth engaging with the CNB community on. 

Slack thread: https://paketobuildpacks.slack.com/archives/C011S6EL49L/p1594148632196100

**Comment by ryanmoran** [comment] 2020-10-23 22:20
I believe this is being looked into at the lifecycle level: https://github.com/buildpacks/imgutil/issues/63. Maybe we can close this issue?

**Closed** 2020-10-28 22:53 UTC
Labels: needs triage
